---

- name: FirewallD rules
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{item.port}}/{{item.proto}}"
    state: "{{item.state}}"
    zone: "{{item.zone}}"
  with_items:
   - {port: "80", proto: "tcp", state: "enabled", zone: "public" }
   - {port: "22", proto: "tcp", state: "enabled", zone: "public" }